name: integrate
channels:
  - anaconda
  - defaults
  - conda-forge
  - bioconda
  - bioinfo
dependencies:
  - cmake=3.18.2
  - conda-forge::parallel=20210822
  - conda-forge::boost=1.76.0
  - bioconda::samtools=1.14
  - bioconda::bowtie2=2.4.4
  - bioconda::bwa=0.7.17
  