name: integrate
channels:
  - anaconda
  - defaults
  - conda-forge
  - bioconda
  - bioinfo
dependencies:
  - anaconda::cmake=3.19.6
  - conda-forge::gdown=3.13.0
  - conda-forge::parallel=20210822
  - conda-forge::boost=1.76.0
  - bioconda::samtools=1.13
  - bioconda::bowtie2=2.4.4
  